algoritmo "semnome"
// Função :
// Autor :
// Data : 04/06/24
// Seção de Declarações 
var

   cor : caractere
inicio

      Escreval ("Digite uma cor: ")
      Leia(cor)

      Se ( cor = "roxo") Entao
      
      Escreval (" A cor digitada é roxo")
      
      Senao
      
      Se ( cor = "verde") Entao
      
        Escreval (" A cor digitada é VERDE")

        Senao
        
        Escreval ("Cor inválida!!!")
      
      FimSE
      
       FimSE
      
      

      

fimalgoritmo
