algoritmo "Função Se e E"
// Função :
// Autor :
// Data : 04/06/24
// Seção de Declarações 
var

   numero: inteiro
inicio

      escreval ("Digite um numero: ")
      leia (numero)
      
      Se (numero >= 2 ) e (numero <= 10 ) Entao
      escreval ("O ", numero, "está no intervalo de 2 a 10")
      
      Senao
      
          escreval ("O numero digitado está fora do intervalo de 2 a 10")
      
      FimSE


fimalgoritmo
