algoritmo "Função Se com Ou"
// Função :
// Autor :
// Data : 04/06/24
// Seção de Declarações 
var

         cor: caractere

inicio

         Escreval("Digite uma cor: ")
         Leia (cor)
         
         Se (cor = "roxo") ou (cor = "verde") Entao

         Escreval ("A cor digitada e Roxo ou verde")
         
         Senao
         
         Escreval ("cor inválida!!!")
         
         
          FimSE

fimalgoritmo
